all:
	xelatex -shell-escape /Users/Corn/Desktop/Code/ACM_SCL/main.tex
	xelatex -shell-escape /Users/Corn/Desktop/Code/ACM_SCL/main.tex
	open main.pdf
clean:
	rm main.log main.pdf main.toc main.aux
	rm -rf _minted-main
